info:
  application:
    name: ${project.name}
    version: ${project.version}

spring:
  datasource:
    url: jdbc:p6spy:h2:file:${rootDir}/data/tx;AUTO_SERVER=TRUE
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: sa
    password: sa
    hikari:
      pool-name: default-cp
  h2:
    console:
      enabled: true
      path: /h2-console
  liquibase:
    change-log: classpath:db/changelog.yml
logging:
  level:
    org.springframework.transaction: DEBUG
