info:
  application:
    name: ${project.name}
    version: ${project.version}
management:
  endpoints:
    jmx:
      exposure:
        include:
          - health
          - metrics

logging:
  level:
    org.springframework.transaction: DEBUG
